headless: false
delay: 1
groups:
  - group:
    name: "3-Month Play Pass"
    paymentLink: https://buy.stripe.com/test_7sI9AL17qcPFd7abIV
    checkout: true
    users:
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 1"
      billingAddressLine1: "Shelby Hawkins, 2185 GA HWY 37 W, Moultrie Georgia 31768, United States"
      billingLocality: "Moultrie"
      billingPostalCode: "31768"
      billingCountry: "US"
      state: Georgia
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Vi Le, 1564 Lake Overlook Ct Lawrenceville, GA 30044, 1564 Lake Overlook Ct, Lawrenceville Georgia 30044, United States"
      billingLocality: "Lawrenceville"
      billingPostalCode: "30044"
      billingCountry: "US"
      state: Georgia
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "GESSICA AMBRIS, 1877 Santa Ines Street, Roseville, CA, USA, Roseville California 95747, United States"
      billingLocality: "Roseville"
      billingPostalCode: "95747"
      billingCountry: "US"
      state: California
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "9716 Bowie Way, Stockton, CA, USA"
      billingLocality: Stockton
      billingPostalCode: "95209"
      billingCountry: "US"
      state: California
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "1321 Chatham Heights Rd Martinsville Va 24112"
      billingLocality: "Martinsville"
      billingPostalCode: "24112"
      billingCountry: "US"
      state: "Virginia"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "1650 South Arizona Avenue 89"
      billingLocality: "Chandler"
      billingPostalCode: "85286"
      billingCountry: "US"
      state: "Arizona"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Stacey Grahl, 424 Maryland Ave, Catonsville Maryland 21228, United States"
      billingLocality: "Catonsville"
      billingPostalCode: "21228"
      billingCountry: "US"
      state: "Maryland"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Grant Fong"
      billingAddressLine1: "1729 Arthur St Hollywood, FL 33020"
      billingLocality: "Miami"
      billingPostalCode: "33020"
      billingCountry: "US"
      state: "Florida"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Sayed Abdalnabei, 4297 Express Lane, Sarasota, FL 34249, BAH 306285, Sarasota Florida 34249-2602, United States"
      billingLocality: "Sarasota"
      billingPostalCode: "34249"
      billingCountry: "US"
      state: "Florida"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "6222 North Lowell Avenue, Chicago, IL, USA"
      billingLocality: "Sarasota"
      billingPostalCode: "60646"
      billingCountry: "US"
      state: "Illinois"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "6855 Palmer Park Boulevard, Colorado Springs, CO, USA"
      billingLocality: "Colorado"
      billingPostalCode: "80915"
      state: "Colorado"
  - group:
    name: "12-Month Play Pass"
    checkout: true
    paymentLink: https://buy.stripe.com/test_aEU28jaI05nd9UYdR5
    users:
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 1"
      billingAddressLine1: "Shelby Hawkins, 2185 GA HWY 37 W, Moultrie Georgia 31768, United States"
      billingLocality: "Moultrie"
      billingPostalCode: "31768"
      state: Georgia
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Vi Le, 1564 Lake Overlook Ct Lawrenceville, GA 30044, 1564 Lake Overlook Ct, Lawrenceville Georgia 30044, United States"
      billingLocality: "Lawrenceville"
      billingPostalCode: "30044"
      state: Georgia
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "GESSICA AMBRIS, 1877 Santa Ines Street, Roseville, CA, USA, Roseville California 95747, United States"
      billingLocality: "Roseville"
      billingPostalCode: "95747"
      state: California
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "9716 Bowie Way, Stockton, CA, USA"
      billingLocality: Stockton
      billingPostalCode: "95209"
      state: California
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "1321 Chatham Heights Rd Martinsville Va 24112"
      billingLocality: "Martinsville"
      billingPostalCode: "24112"
      state: "Virginia"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "1650 South Arizona Avenue 89"
      billingLocality: "Chandler"
      billingPostalCode: "85286"
      state: "Arizona"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Stacey Grahl, 424 Maryland Ave, Catonsville Maryland 21228, United States"
      billingLocality: "Catonsville"
      billingPostalCode: "21228"
      state: "Maryland"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Grant Fong"
      billingAddressLine1: "1729 Arthur St Hollywood, FL 33020"
      billingLocality: "Miami"
      billingPostalCode: "33020"
      state: "Florida"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Sayed Abdalnabei, 4297 Express Lane, Sarasota, FL 34249, BAH 306285, Sarasota Florida 34249-2602, United States"
      billingLocality: "Sarasota"
      billingPostalCode: "34249"
      state: "Florida"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "6222 North Lowell Avenue, Chicago, IL, USA"
      billingLocality: "Sarasota"
      billingPostalCode: "60646"
      state: "Illinois"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "6855 Palmer Park Boulevard, Colorado Springs, CO, USA"
      billingLocality: "Colorado"
      billingPostalCode: "80915"
      billingCountry: "US"
      state: "Colorado"
  - group:
    name: "Nex Playground"
    checkout: true
    paymentLink: https://buy.stripe.com/test_28o14f7vOdTJc3614f
    users:
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 1"
      billingAddressLine1: "Shelby Hawkins, 2185 GA HWY 37 W, Moultrie Georgia 31768, United States"
      billingLocality: "Moultrie"
      billingPostalCode: "31768"
      billingCountry: "US"
      state: Georgia
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Vi Le, 1564 Lake Overlook Ct Lawrenceville, GA 30044, 1564 Lake Overlook Ct, Lawrenceville Georgia 30044, United States"
      billingLocality: "Lawrenceville"
      billingPostalCode: "30044"
      billingCountry: "US"
      state: Georgia
    - email: "grant@nex.team"
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "GESSICA AMBRIS, 1877 Santa Ines Street, Roseville, CA, USA, Roseville California 95747, United States"
      billingLocality: "Roseville"
      billingPostalCode: "95747"
      billingCountry: "US"
      state: California
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "9716 Bowie Way, Stockton, CA, USA"
      billingLocality: Stockton
      billingPostalCode: "95209"
      billingCountry: "US"
      state: California

    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "1321 Chatham Heights Rd Martinsville Va 24112"
      billingLocality: "Martinsville"
      billingPostalCode: "24112"
      billingCountry: "US"
      state: "Virginia"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "1650 South Arizona Avenue 89"
      billingLocality: "Chandler"
      billingPostalCode: "85286"
      billingCountry: "US"
      state: "Arizona"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Stacey Grahl, 424 Maryland Ave, Catonsville Maryland 21228, United States"
      billingLocality: "Catonsville"
      billingPostalCode: "21228"
      billingCountry: "US"
      state: "Maryland"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Grant Fong"
      billingAddressLine1: "1729 Arthur St Hollywood, FL 33020"
      billingLocality: "Miami"
      billingPostalCode: "33020"
      billingCountry: "US"
      state: "Florida"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "Sayed Abdalnabei, 4297 Express Lane, Sarasota, FL 34249, BAH 306285, Sarasota Florida 34249-2602, United States"
      billingLocality: "Sarasota"
      billingPostalCode: "34249"
      billingCountry: "US"
      state: "Florida"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "6222 North Lowell Avenue, Chicago, IL, USA"
      billingLocality: "Sarasota"
      billingPostalCode: "60646"
      billingCountry: "US"
      state: "Illinois"
    - email: grant@nex.team
      cardNumber: "4242424242424242"
      cardExpiry: "0129"
      cardCvc: "123"
      billingName: "Test User 2"
      billingAddressLine1: "6855 Palmer Park Boulevard, Colorado Springs, CO, USA"
      billingLocality: "Colorado"
      billingPostalCode: "80915"
      billingCountry: "US"
      state: "Colorado"